def main():
    data = [{"word":"old","score":1001},{"word":"ancient","score":1000},{"word":"modern","score":999},{"word":"early","score":998},{"word":"century","score":997},{"word":"native","score":996},{"word":"beautiful","score":995},{"word":"real","score":994},{"word":"california","score":993},{"word":"contemporary","score":992},{"word":"distant","score":991},{"word":"day","score":990},{"word":"tropical","score":989},{"word":"prehistoric","score":988},{"word":"rural","score":987},{"word":"japan","score":986},{"word":"sunny","score":985},{"word":"independent","score":984},{"word":"southern","score":983},{"word":"novel","score":982},{"word":"western","score":981},{"word":"canadafrance","score":980},{"word":"wartime","score":979},{"word":"byu","score":978},{"word":"postwar","score":977},{"word":"precontact","score":976},{"word":"off","score":975},{"word":"mainland","score":974},{"word":"traditional","score":973},{"word":"aboriginal","score":972},{"word":"eastern","score":971},{"word":"west","score":970},{"word":"northern","score":969},{"word":"beloved","score":968},{"word":"primitive","score":967},{"word":"multicultural","score":966},{"word":"exotic","score":965},{"word":"prewar","score":964},{"word":"coast","score":963},{"word":"night","score":962},{"word":"war","score":961},{"word":"blue","score":960},{"word":"faraway","score":959},{"word":"fair","score":958},{"word":"19th","score":957},{"word":"emperor","score":956},{"word":"romantic","score":955},{"word":"angeles","score":954},{"word":"away","score":953},{"word":"japanese","score":952},{"word":"balmy","score":951},{"word":"remote","score":950},{"word":"precolonial","score":949},{"word":"hawaiian","score":948},{"word":"united","score":947},{"word":"colonial","score":946},{"word":"peaceful","score":945},{"word":"nineteenth","score":944},{"word":"twentieth","score":943},{"word":"multiethnic","score":942},{"word":"tahiti","score":941},{"word":"multiracial","score":940},{"word":"time","score":939},{"word":"all","score":938},{"word":"southeastern","score":937},{"word":"lovely","score":936},{"word":"south","score":935},{"word":"nearby","score":934},{"word":"feudal","score":933},{"word":"territorial","score":932},{"word":"pagan","score":931},{"word":"history","score":930},{"word":"historic","score":929},{"word":"lush","score":928}]

    objective_list = []
    # TODO: Iterate over the data and extract the adjectives for the word and store them in the list variable
    for item in data:
        objective_list.append(item["word"])
    # TODO: Print the list variable, Example of print: Adjectives for the word "word" are: [list of adjectives]
    print(f"Adjectives for the word 'word' are: {objective_list}")

if __name__ == '__main__':
    main()